networks:
  dev:

services:
  database:
    image: postgres
    container_name: database

    ports:
      - "${POSTGRES_PORT:-5432}:5432"    
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-db}

    networks:
      - dev

  backend:
    build:
      context: ./backend
      target: ${TARGET:-prod}
    container_name: backend_container

    ports:
      - "${SWAGGER_PORT:-8000}:8000"
    environment:
      DB_PATH: postgresql+asyncpg://postgres:admin@database/${DB_NAME:-db}
      DB_ECHO: 1 
      API_PATH: /api
    depends_on:
      - database
    restart: always

    networks:
      - dev

  bot:
    build:
      context: ./bot
      target: ${TARGET:-prod}
    container_name: bot_container

    environment:
      BOT_TOKEN: ${BOT_TOKEN:-1234567890:AABBccddeeffgghhjj-AAbbccddeeffgghh}
      API_URL: "http://backend:${SWAGGER_PORT:-8000}/api"
      ADMIN_ID: ${ADMIN_ID:-123456789}
    depends_on:
      - backend
    restart: always

    networks:
      - dev