networks:
  dev:

services:
  database:
    image: postgres
    container_name: database

    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}   
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-db}

    networks:
      - dev
  
  backend:
    build:
      context: ./backend
    container_name: backend_container

    ports:
      - ${SWAGGER_PORT:-8000}:${SWAGGER_PORT:-8000}
    environment:
      DB_PATH: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-admin}@database/${POSTGRES_DB:-db}
      DB_ECHO: ${DB_ECHO:-1}
      API_PATH: ${API_PATH:-/api}
    depends_on:
      - database
    restart: always

    networks:
      - dev

  bot:
    build:
      context: ./bot
    container_name: bot_container

    environment:
      BOT_TOKEN: ${BOT_TOKEN:-1234567890:AABBccddeeffgghhjj-AAbbccddeeffgghh}
      DB_API: "http://backend:${SWAGGER_PORT:-8000}/api"
      AWG_API: ${AWG_API:-http://localhost:51821/api/wireguard}
      ADMIN_ID: ${ADMIN_ID:-123456789}
    depends_on:
      - backend
    restart: always

    networks:
      - dev